{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "955be24c",
   "metadata": {},
   "source": [
    "## Generate a dataset with 10 features, 1 regression target, 150 000 rows"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "17015d36",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>pregnancies</th>\n",
       "      <th>glucose</th>\n",
       "      <th>blood_pressure</th>\n",
       "      <th>skin_thickness</th>\n",
       "      <th>insulin</th>\n",
       "      <th>age</th>\n",
       "      <th>sex</th>\n",
       "      <th>body_mass_index</th>\n",
       "      <th>pedigree_function</th>\n",
       "      <th>blood_sugar</th>\n",
       "      <th>target</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>6.4</td>\n",
       "      <td>91</td>\n",
       "      <td>9</td>\n",
       "      <td>67</td>\n",
       "      <td>45</td>\n",
       "      <td>False</td>\n",
       "      <td>28</td>\n",
       "      <td>False</td>\n",
       "      <td>20</td>\n",
       "      <td>25</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>6.7</td>\n",
       "      <td>97</td>\n",
       "      <td>64</td>\n",
       "      <td>61</td>\n",
       "      <td>48</td>\n",
       "      <td>False</td>\n",
       "      <td>15</td>\n",
       "      <td>False</td>\n",
       "      <td>35</td>\n",
       "      <td>25</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>0</td>\n",
       "      <td>4.2</td>\n",
       "      <td>108</td>\n",
       "      <td>54</td>\n",
       "      <td>65</td>\n",
       "      <td>60</td>\n",
       "      <td>True</td>\n",
       "      <td>20</td>\n",
       "      <td>False</td>\n",
       "      <td>49</td>\n",
       "      <td>30</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>5</td>\n",
       "      <td>5.7</td>\n",
       "      <td>60</td>\n",
       "      <td>97</td>\n",
       "      <td>123</td>\n",
       "      <td>49</td>\n",
       "      <td>False</td>\n",
       "      <td>27</td>\n",
       "      <td>True</td>\n",
       "      <td>39</td>\n",
       "      <td>70</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>0</td>\n",
       "      <td>3.0</td>\n",
       "      <td>103</td>\n",
       "      <td>24</td>\n",
       "      <td>90</td>\n",
       "      <td>39</td>\n",
       "      <td>True</td>\n",
       "      <td>18</td>\n",
       "      <td>False</td>\n",
       "      <td>45</td>\n",
       "      <td>15</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   pregnancies  glucose  blood_pressure  skin_thickness  insulin  age    sex  \\\n",
       "0            0      6.4              91               9       67   45  False   \n",
       "1            1      6.7              97              64       61   48  False   \n",
       "2            0      4.2             108              54       65   60   True   \n",
       "3            5      5.7              60              97      123   49  False   \n",
       "4            0      3.0             103              24       90   39   True   \n",
       "\n",
       "   body_mass_index  pedigree_function  blood_sugar  target  \n",
       "0               28              False           20      25  \n",
       "1               15              False           35      25  \n",
       "2               20              False           49      30  \n",
       "3               27               True           39      70  \n",
       "4               18              False           45      15  "
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "!pip install faker -q\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from faker import Faker\n",
    "\n",
    "from sklearn import preprocessing\n",
    "\n",
    "faker = Faker()\n",
    "\n",
    "def make_fake_data(num):\n",
    "    fake_data = [{'pregnancies': faker.random_int(0, 5),\n",
    "                  'glucose': faker.pyfloat(min_value=3, max_value=8, right_digits=1),\n",
    "                  'blood_pressure':faker.random_int(60, 120),\n",
    "                  'skin_thickness': faker.random_int(0, 100),\n",
    "                  'insulin': faker.random_int(60, 140),\n",
    "                  'age': faker.random_int(21, 80),\n",
    "                  'sex': faker.boolean(),\n",
    "                  'body_mass_index': faker.random_int(15, 35),\n",
    "                  'pedigree_function': faker.boolean(), \n",
    "                  'blood_sugar': faker.random_int(10, 60),\n",
    "                  'target':0} for x in range(num)]\n",
    "    return fake_data\n",
    "\n",
    "# Genearte fake data\n",
    "num=150000\n",
    "df = pd.DataFrame(make_fake_data(num))\n",
    "df.head()\n",
    "\n",
    "# Buld a relationship\n",
    "for i in range(num):\n",
    "    results=0\n",
    "    if df.iloc[i]['sex'] == 1:\n",
    "        results += 5\n",
    "    if df.iloc[i]['pedigree_function'] == 1:\n",
    "        results += 10\n",
    "        df.at[i,'blood_pressure']=np.random.randint(60, 90)\n",
    "    else:\n",
    "        df.at[i,'blood_pressure']=np.random.randint(90, 120)\n",
    "    if df.iloc[i]['glucose'] > 5:\n",
    "        results += 10\n",
    "    if df.iloc[i]['body_mass_index'] > 20:\n",
    "        results += 5\n",
    "    if df.iloc[i]['skin_thickness'] > 50:\n",
    "        results += 5\n",
    "    if df.iloc[i]['insulin'] > 100:\n",
    "        df.at[i,'blood_pressure']=np.random.randint(60, 90)\n",
    "        results += 10\n",
    "    if df.iloc[i]['age'] > 50:\n",
    "        results += 10\n",
    "    if df.iloc[i]['blood_sugar'] > 6:\n",
    "        results += 10\n",
    "    if df.iloc[i]['blood_pressure'] < 90:\n",
    "        results += 10\n",
    "    if df.iloc[i]['pregnancies'] > 3:\n",
    "        results += 10\n",
    "    df.at[i,'target']=results\n",
    "      \n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "e8e47b77",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>pregnancies</th>\n",
       "      <th>glucose</th>\n",
       "      <th>blood_pressure</th>\n",
       "      <th>skin_thickness</th>\n",
       "      <th>insulin</th>\n",
       "      <th>age</th>\n",
       "      <th>sex</th>\n",
       "      <th>body_mass_index</th>\n",
       "      <th>pedigree_function</th>\n",
       "      <th>blood_sugar</th>\n",
       "      <th>target</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0.0</td>\n",
       "      <td>0.693878</td>\n",
       "      <td>0.525424</td>\n",
       "      <td>0.09</td>\n",
       "      <td>0.0875</td>\n",
       "      <td>0.406780</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.65</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.20</td>\n",
       "      <td>0.200000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>0.2</td>\n",
       "      <td>0.755102</td>\n",
       "      <td>0.627119</td>\n",
       "      <td>0.64</td>\n",
       "      <td>0.0125</td>\n",
       "      <td>0.457627</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.50</td>\n",
       "      <td>0.200000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>0.0</td>\n",
       "      <td>0.244898</td>\n",
       "      <td>0.813559</td>\n",
       "      <td>0.54</td>\n",
       "      <td>0.0625</td>\n",
       "      <td>0.661017</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.25</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.78</td>\n",
       "      <td>0.266667</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1.0</td>\n",
       "      <td>0.551020</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.97</td>\n",
       "      <td>0.7875</td>\n",
       "      <td>0.474576</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.60</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.58</td>\n",
       "      <td>0.800000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>0.0</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.728814</td>\n",
       "      <td>0.24</td>\n",
       "      <td>0.3750</td>\n",
       "      <td>0.305085</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.15</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.70</td>\n",
       "      <td>0.066667</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   pregnancies   glucose  blood_pressure  skin_thickness  insulin       age  \\\n",
       "0          0.0  0.693878        0.525424            0.09   0.0875  0.406780   \n",
       "1          0.2  0.755102        0.627119            0.64   0.0125  0.457627   \n",
       "2          0.0  0.244898        0.813559            0.54   0.0625  0.661017   \n",
       "3          1.0  0.551020        0.000000            0.97   0.7875  0.474576   \n",
       "4          0.0  0.000000        0.728814            0.24   0.3750  0.305085   \n",
       "\n",
       "   sex  body_mass_index  pedigree_function  blood_sugar    target  \n",
       "0  0.0             0.65                0.0         0.20  0.200000  \n",
       "1  0.0             0.00                0.0         0.50  0.200000  \n",
       "2  1.0             0.25                0.0         0.78  0.266667  \n",
       "3  0.0             0.60                1.0         0.58  0.800000  \n",
       "4  1.0             0.15                0.0         0.70  0.066667  "
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Transform features by scaling each feature to a given range (MinMaxScaler)      \n",
    "x = df.values\n",
    "min_max_scaler = preprocessing.MinMaxScaler()\n",
    "x_scaled = min_max_scaler.fit_transform(x)\n",
    "df = pd.DataFrame(x_scaled)\n",
    "df.columns = ['pregnancies', 'glucose', 'blood_pressure', 'skin_thickness', 'insulin', 'age', 'sex','body_mass_index', 'pedigree_function', 'blood_sugar', 'target']\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "468fabc3",
   "metadata": {},
   "source": [
    "## Design Linear Regression"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "fa50a80e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train X = 80%\n",
      "Train Y = 80%\n",
      "Test X = 20%\n",
      "Test Y = 20%\n",
      "__________________________________\n",
      "MSE: 0.006295969155164378\n",
      "__________________________________\n"
     ]
    }
   ],
   "source": [
    "from sklearn import metrics\n",
    "from sklearn.metrics import mean_squared_error\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.linear_model import LinearRegression\n",
    "\n",
    "def print_evaluate(true, predicted):  \n",
    "    mse = mean_squared_error(true, predicted)\n",
    "    print('MSE:', mse)\n",
    "    print('__________________________________')\n",
    "    \n",
    "X = df[['pregnancies', 'glucose', 'blood_pressure', 'skin_thickness', 'insulin', 'age', 'sex','body_mass_index', 'pedigree_function', 'blood_sugar']]\n",
    "y = df['target']\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)\n",
    "\n",
    "print(f'Train X = {round(X_train.shape[0]/df.shape[0]*100)}%')\n",
    "print(f'Train Y = {round(y_train.shape[0]/df.shape[0]*100)}%')\n",
    "print(f'Test X = {round(X_test.shape[0]/df.shape[0]*100)}%')\n",
    "print(f'Test Y = {round(y_test.shape[0]/df.shape[0]*100)}%')\n",
    "print('__________________________________')\n",
    "\n",
    "lin_reg = LinearRegression(normalize=True)\n",
    "lin_reg.fit(X_train,y_train)\n",
    "pred = lin_reg.predict(X_test)\n",
    "print_evaluate(y_test, pred)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a8d0005e",
   "metadata": {},
   "source": [
    "## Design 3 Dense Neural Networks (1, 5, 25 hidden layers). \n",
    "## Prepare 3 optimizers:\n",
    "- (OPT1) SGD\n",
    "- (OPT2) RMSProp\n",
    "- (OPT3) Adam\n",
    "\n",
    "\n",
    "## Explore the following learning rates:\n",
    "- (lr1) 0.1\n",
    "- (lr2) 0.01\n",
    "- (lr3) 0.001"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "4ce77d79",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3341/3375 [============================>.] - ETA: 0s - loss: 0.0076 - mean_squared_error: 0.0076WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0075 - mean_squared_error: 0.0075 - val_loss: 0.0062 - val_mean_squared_error: 0.0062\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0062 - mean_squared_error: 0.0062 - val_loss: 0.0062 - val_mean_squared_error: 0.0062\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0056 - mean_squared_error: 0.0056 - val_loss: 0.0056 - val_mean_squared_error: 0.0056\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0050 - mean_squared_error: 0.0050 - val_loss: 0.0047 - val_mean_squared_error: 0.0047\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0048 - mean_squared_error: 0.0048 - val_loss: 0.0052 - val_mean_squared_error: 0.0052\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0047 - mean_squared_error: 0.0047 - val_loss: 0.0044 - val_mean_squared_error: 0.0044\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0046 - mean_squared_error: 0.0046 - val_loss: 0.0044 - val_mean_squared_error: 0.0044\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0045 - mean_squared_error: 0.0045 - val_loss: 0.0043 - val_mean_squared_error: 0.0043\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0045 - mean_squared_error: 0.0045 - val_loss: 0.0049 - val_mean_squared_error: 0.0049\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0045 - mean_squared_error: 0.0045 - val_loss: 0.0042 - val_mean_squared_error: 0.0042\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_3_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_3_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3371/3375 [============================>.] - ETA: 0s - loss: 0.3440 - mean_squared_error: 0.3440WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_3_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3440 - mean_squared_error: 0.3440 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 5s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_6_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_6_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3364/3375 [============================>.] - ETA: 0s - loss: 0.3240 - mean_squared_error: 0.3240WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_6_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3241 - mean_squared_error: 0.3241 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_9_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_9_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3370/3375 [============================>.] - ETA: 0s - loss: 0.0146 - mean_squared_error: 0.0146WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_9_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0146 - mean_squared_error: 0.0146 - val_loss: 0.0073 - val_mean_squared_error: 0.0073\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0069 - mean_squared_error: 0.0069 - val_loss: 0.0065 - val_mean_squared_error: 0.0065\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0065 - mean_squared_error: 0.0065 - val_loss: 0.0063 - val_mean_squared_error: 0.0063\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0064 - mean_squared_error: 0.0064 - val_loss: 0.0063 - val_mean_squared_error: 0.0063\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0064 - mean_squared_error: 0.0064 - val_loss: 0.0063 - val_mean_squared_error: 0.0063\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0064 - mean_squared_error: 0.0064 - val_loss: 0.0062 - val_mean_squared_error: 0.0062\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0063 - mean_squared_error: 0.0063 - val_loss: 0.0062 - val_mean_squared_error: 0.0062\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0063 - mean_squared_error: 0.0063 - val_loss: 0.0062 - val_mean_squared_error: 0.0062\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 6s 2ms/step - loss: 0.0063 - mean_squared_error: 0.0063 - val_loss: 0.0062 - val_mean_squared_error: 0.0062\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0063 - mean_squared_error: 0.0063 - val_loss: 0.0061 - val_mean_squared_error: 0.0061\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_12_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_12_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3352/3375 [============================>.] - ETA: 0s - loss: 0.0071 - mean_squared_error: 0.0071WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_12_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0071 - mean_squared_error: 0.0071 - val_loss: 0.0042 - val_mean_squared_error: 0.0042\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0046 - mean_squared_error: 0.0046 - val_loss: 0.0036 - val_mean_squared_error: 0.0036\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0036 - mean_squared_error: 0.0036 - val_loss: 0.0065 - val_mean_squared_error: 0.0065\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0032 - mean_squared_error: 0.0032 - val_loss: 0.0022 - val_mean_squared_error: 0.0022\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0030 - mean_squared_error: 0.0030 - val_loss: 0.0023 - val_mean_squared_error: 0.0023\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0026 - mean_squared_error: 0.0026 - val_loss: 0.0019 - val_mean_squared_error: 0.0019\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0025 - mean_squared_error: 0.0025 - val_loss: 0.0033 - val_mean_squared_error: 0.0033\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0025 - mean_squared_error: 0.0025 - val_loss: 0.0020 - val_mean_squared_error: 0.0020\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0025 - mean_squared_error: 0.0025 - val_loss: 0.0033 - val_mean_squared_error: 0.0033\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0023 - mean_squared_error: 0.0023 - val_loss: 0.0027 - val_mean_squared_error: 0.0027\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_15_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_15_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3366/3375 [============================>.] - ETA: 0s - loss: 0.0066 - mean_squared_error: 0.0066WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_15_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0066 - mean_squared_error: 0.0066 - val_loss: 0.0046 - val_mean_squared_error: 0.0046\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0042 - mean_squared_error: 0.0042 - val_loss: 0.0038 - val_mean_squared_error: 0.0038\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0040 - mean_squared_error: 0.0040 - val_loss: 0.0038 - val_mean_squared_error: 0.0038\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0039 - mean_squared_error: 0.0039 - val_loss: 0.0041 - val_mean_squared_error: 0.0041\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0038 - mean_squared_error: 0.0038 - val_loss: 0.0036 - val_mean_squared_error: 0.0036\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0038 - mean_squared_error: 0.0038 - val_loss: 0.0035 - val_mean_squared_error: 0.0035\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0038 - mean_squared_error: 0.0038 - val_loss: 0.0043 - val_mean_squared_error: 0.0043\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0037 - mean_squared_error: 0.0037 - val_loss: 0.0035 - val_mean_squared_error: 0.0035\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0038 - mean_squared_error: 0.0038 - val_loss: 0.0043 - val_mean_squared_error: 0.0043\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0037 - mean_squared_error: 0.0037 - val_loss: 0.0037 - val_mean_squared_error: 0.0037\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_18_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_18_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3344/3375 [============================>.] - ETA: 0s - loss: 0.0467 - mean_squared_error: 0.0467WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_18_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0465 - mean_squared_error: 0.0465 - val_loss: 0.0279 - val_mean_squared_error: 0.0279\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0248 - mean_squared_error: 0.0248 - val_loss: 0.0224 - val_mean_squared_error: 0.0224\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0202 - mean_squared_error: 0.0202 - val_loss: 0.0186 - val_mean_squared_error: 0.0186\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0169 - mean_squared_error: 0.0169 - val_loss: 0.0158 - val_mean_squared_error: 0.0158\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0145 - mean_squared_error: 0.0145 - val_loss: 0.0137 - val_mean_squared_error: 0.0137\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0127 - mean_squared_error: 0.0127 - val_loss: 0.0121 - val_mean_squared_error: 0.0121\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0113 - mean_squared_error: 0.0113 - val_loss: 0.0109 - val_mean_squared_error: 0.0109\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0103 - mean_squared_error: 0.0103 - val_loss: 0.0100 - val_mean_squared_error: 0.0100\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0095 - mean_squared_error: 0.0095 - val_loss: 0.0093 - val_mean_squared_error: 0.0093\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0089 - mean_squared_error: 0.0089 - val_loss: 0.0088 - val_mean_squared_error: 0.0088\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_21_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_21_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3351/3375 [============================>.] - ETA: 0s - loss: 0.3227 - mean_squared_error: 0.3227WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_21_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_24_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_24_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3345/3375 [============================>.] - ETA: 0s - loss: 0.0076 - mean_squared_error: 0.0076WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_24_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0076 - mean_squared_error: 0.0076 - val_loss: 0.0058 - val_mean_squared_error: 0.0058\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0057 - mean_squared_error: 0.0057 - val_loss: 0.0056 - val_mean_squared_error: 0.0056\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0051 - mean_squared_error: 0.0051 - val_loss: 0.0048 - val_mean_squared_error: 0.0048\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0046 - mean_squared_error: 0.0046 - val_loss: 0.0042 - val_mean_squared_error: 0.0042\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0041 - mean_squared_error: 0.0041 - val_loss: 0.0039 - val_mean_squared_error: 0.0039\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0039 - mean_squared_error: 0.0039 - val_loss: 0.0038 - val_mean_squared_error: 0.0038\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0038 - mean_squared_error: 0.0038 - val_loss: 0.0036 - val_mean_squared_error: 0.0036\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0033 - mean_squared_error: 0.0033 - val_loss: 0.0029 - val_mean_squared_error: 0.0029\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0028 - mean_squared_error: 0.0028 - val_loss: 0.0025 - val_mean_squared_error: 0.0025\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0024 - mean_squared_error: 0.0024 - val_loss: 0.0023 - val_mean_squared_error: 0.0023\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_27_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_27_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3345/3375 [============================>.] - ETA: 0s - loss: 0.3227 - mean_squared_error: 0.3227WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_27_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_34_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_34_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - ETA: 0s - loss: 1.8804 - mean_squared_error: 1.8804WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_34_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 1.8804 - mean_squared_error: 1.8804 - val_loss: 0.0391 - val_mean_squared_error: 0.0391\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0404 - mean_squared_error: 0.0404 - val_loss: 0.0380 - val_mean_squared_error: 0.0380\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0404 - mean_squared_error: 0.0404 - val_loss: 0.0471 - val_mean_squared_error: 0.0471\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0404 - mean_squared_error: 0.0404 - val_loss: 0.0378 - val_mean_squared_error: 0.0378\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0404 - mean_squared_error: 0.0404 - val_loss: 0.0442 - val_mean_squared_error: 0.0442\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0404 - mean_squared_error: 0.0404 - val_loss: 0.0372 - val_mean_squared_error: 0.0372\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0404 - mean_squared_error: 0.0404 - val_loss: 0.0419 - val_mean_squared_error: 0.0419\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0404 - mean_squared_error: 0.0404 - val_loss: 0.0379 - val_mean_squared_error: 0.0379\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0404 - mean_squared_error: 0.0404 - val_loss: 0.0374 - val_mean_squared_error: 0.0374\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0404 - mean_squared_error: 0.0404 - val_loss: 0.0379 - val_mean_squared_error: 0.0379\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_41_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_41_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3369/3375 [============================>.] - ETA: 0s - loss: 0.0254 - mean_squared_error: 0.0254WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_41_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Callbacks method `on_test_batch_begin` is slow compared to the batch time (batch time: 0.0000s vs `on_test_batch_begin` time: 0.0010s). Check your callbacks.\n",
      "WARNING:tensorflow:Callbacks method `on_test_batch_end` is slow compared to the batch time (batch time: 0.0000s vs `on_test_batch_end` time: 0.0010s). Check your callbacks.\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0254 - mean_squared_error: 0.0254 - val_loss: 0.0273 - val_mean_squared_error: 0.0273\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0216 - mean_squared_error: 0.0216 - val_loss: 0.0218 - val_mean_squared_error: 0.0218\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0126 - mean_squared_error: 0.0126 - val_loss: 0.0064 - val_mean_squared_error: 0.0064\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0086 - mean_squared_error: 0.0086 - val_loss: 0.0089 - val_mean_squared_error: 0.0089\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0087 - mean_squared_error: 0.0087 - val_loss: 0.0077 - val_mean_squared_error: 0.0077\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0087 - mean_squared_error: 0.0087 - val_loss: 0.0081 - val_mean_squared_error: 0.0081\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0083 - mean_squared_error: 0.0083 - val_loss: 0.0062 - val_mean_squared_error: 0.0062\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0088 - mean_squared_error: 0.0088 - val_loss: 0.0073 - val_mean_squared_error: 0.0073\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0086 - mean_squared_error: 0.0086 - val_loss: 0.0067 - val_mean_squared_error: 0.0067\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0086 - mean_squared_error: 0.0086 - val_loss: 0.0069 - val_mean_squared_error: 0.0069\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_48_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_48_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3365/3375 [============================>.] - ETA: 0s - loss: 0.0254 - mean_squared_error: 0.0254WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_48_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0254 - mean_squared_error: 0.0254 - val_loss: 0.0115 - val_mean_squared_error: 0.0115\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0089 - mean_squared_error: 0.0089 - val_loss: 0.0074 - val_mean_squared_error: 0.0074\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0072 - mean_squared_error: 0.0072 - val_loss: 0.0069 - val_mean_squared_error: 0.0069\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0068 - mean_squared_error: 0.0068 - val_loss: 0.0065 - val_mean_squared_error: 0.0065\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0066 - mean_squared_error: 0.0066 - val_loss: 0.0064 - val_mean_squared_error: 0.0064\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0065 - mean_squared_error: 0.0065 - val_loss: 0.0063 - val_mean_squared_error: 0.0063\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0064 - mean_squared_error: 0.0064 - val_loss: 0.0062 - val_mean_squared_error: 0.0062\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0063 - mean_squared_error: 0.0063 - val_loss: 0.0061 - val_mean_squared_error: 0.0061\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0062 - mean_squared_error: 0.0062 - val_loss: 0.0061 - val_mean_squared_error: 0.0061\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0062 - mean_squared_error: 0.0062 - val_loss: 0.0060 - val_mean_squared_error: 0.0060\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_55_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_55_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3351/3375 [============================>.] - ETA: 0s - loss: 0.0073 - mean_squared_error: 0.0073WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_55_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0072 - mean_squared_error: 0.0072 - val_loss: 0.0073 - val_mean_squared_error: 0.0073\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0044 - mean_squared_error: 0.0044 - val_loss: 0.0036 - val_mean_squared_error: 0.0036\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0035 - mean_squared_error: 0.0035 - val_loss: 0.0026 - val_mean_squared_error: 0.0026\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0030 - mean_squared_error: 0.0030 - val_loss: 0.0026 - val_mean_squared_error: 0.0026\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0027 - mean_squared_error: 0.0027 - val_loss: 0.0040 - val_mean_squared_error: 0.0040\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0025 - mean_squared_error: 0.0025 - val_loss: 0.0023 - val_mean_squared_error: 0.0023\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0025 - mean_squared_error: 0.0025 - val_loss: 0.0018 - val_mean_squared_error: 0.0018\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0024 - mean_squared_error: 0.0024 - val_loss: 0.0027 - val_mean_squared_error: 0.0027\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0023 - mean_squared_error: 0.0023 - val_loss: 0.0021 - val_mean_squared_error: 0.0021\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0022 - mean_squared_error: 0.0022 - val_loss: 0.0050 - val_mean_squared_error: 0.0050\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_62_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_62_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3361/3375 [============================>.] - ETA: 0s - loss: 0.0982 - mean_squared_error: 0.0982WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_62_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0978 - mean_squared_error: 0.0978 - val_loss: 0.0052 - val_mean_squared_error: 0.0052\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0052 - mean_squared_error: 0.0052 - val_loss: 0.0047 - val_mean_squared_error: 0.0047\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0050 - mean_squared_error: 0.0050 - val_loss: 0.0056 - val_mean_squared_error: 0.0056\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0050 - mean_squared_error: 0.0050 - val_loss: 0.0047 - val_mean_squared_error: 0.0047\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0049 - mean_squared_error: 0.0049 - val_loss: 0.0047 - val_mean_squared_error: 0.0047\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0050 - mean_squared_error: 0.0050 - val_loss: 0.0046 - val_mean_squared_error: 0.0046\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0050 - mean_squared_error: 0.0050 - val_loss: 0.0046 - val_mean_squared_error: 0.0046\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0050 - mean_squared_error: 0.0050 - val_loss: 0.0062 - val_mean_squared_error: 0.0062\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0049 - mean_squared_error: 0.0049 - val_loss: 0.0047 - val_mean_squared_error: 0.0047\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0049 - mean_squared_error: 0.0049 - val_loss: 0.0053 - val_mean_squared_error: 0.0053\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_69_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_69_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3352/3375 [============================>.] - ETA: 0s - loss: 0.0314 - mean_squared_error: 0.0314WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_69_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0313 - mean_squared_error: 0.0313 - val_loss: 0.0237 - val_mean_squared_error: 0.0237\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0211 - mean_squared_error: 0.0211 - val_loss: 0.0189 - val_mean_squared_error: 0.0189\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0173 - mean_squared_error: 0.0173 - val_loss: 0.0159 - val_mean_squared_error: 0.0159\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0147 - mean_squared_error: 0.0147 - val_loss: 0.0136 - val_mean_squared_error: 0.0136\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0127 - mean_squared_error: 0.0127 - val_loss: 0.0118 - val_mean_squared_error: 0.0118\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0112 - mean_squared_error: 0.0112 - val_loss: 0.0105 - val_mean_squared_error: 0.0105\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0100 - mean_squared_error: 0.0100 - val_loss: 0.0094 - val_mean_squared_error: 0.0094\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0091 - mean_squared_error: 0.0091 - val_loss: 0.0087 - val_mean_squared_error: 0.0087\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0085 - mean_squared_error: 0.0085 - val_loss: 0.0081 - val_mean_squared_error: 0.0081\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0081 - mean_squared_error: 0.0081 - val_loss: 0.0078 - val_mean_squared_error: 0.0078\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_76_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_76_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3364/3375 [============================>.] - ETA: 0s - loss: 0.0073 - mean_squared_error: 0.0073WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_76_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0073 - mean_squared_error: 0.0073 - val_loss: 0.0045 - val_mean_squared_error: 0.0045\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0044 - mean_squared_error: 0.0044 - val_loss: 0.0045 - val_mean_squared_error: 0.0045\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 5s 2ms/step - loss: 0.0041 - mean_squared_error: 0.0041 - val_loss: 0.0038 - val_mean_squared_error: 0.0038\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0039 - mean_squared_error: 0.0039 - val_loss: 0.0036 - val_mean_squared_error: 0.0036\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 5s 2ms/step - loss: 0.0037 - mean_squared_error: 0.0037 - val_loss: 0.0036 - val_mean_squared_error: 0.0036\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0036 - mean_squared_error: 0.0036 - val_loss: 0.0035 - val_mean_squared_error: 0.0035\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0035 - mean_squared_error: 0.0035 - val_loss: 0.0033 - val_mean_squared_error: 0.0033\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0035 - mean_squared_error: 0.0035 - val_loss: 0.0037 - val_mean_squared_error: 0.0037\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0034 - mean_squared_error: 0.0034 - val_loss: 0.0035 - val_mean_squared_error: 0.0035\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0034 - mean_squared_error: 0.0034 - val_loss: 0.0033 - val_mean_squared_error: 0.0033\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_83_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_83_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3343/3375 [============================>.] - ETA: 0s - loss: 0.0091 - mean_squared_error: 0.0091WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_83_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0091 - mean_squared_error: 0.0091 - val_loss: 0.0044 - val_mean_squared_error: 0.0044\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0041 - mean_squared_error: 0.0041 - val_loss: 0.0036 - val_mean_squared_error: 0.0036\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0032 - mean_squared_error: 0.0032 - val_loss: 0.0027 - val_mean_squared_error: 0.0027\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 4s 1ms/step - loss: 0.0025 - mean_squared_error: 0.0025 - val_loss: 0.0022 - val_mean_squared_error: 0.0022\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0022 - mean_squared_error: 0.0022 - val_loss: 0.0022 - val_mean_squared_error: 0.0022\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0021 - mean_squared_error: 0.0021 - val_loss: 0.0020 - val_mean_squared_error: 0.0020\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0020 - mean_squared_error: 0.0020 - val_loss: 0.0019 - val_mean_squared_error: 0.0019\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0020 - mean_squared_error: 0.0020 - val_loss: 0.0020 - val_mean_squared_error: 0.0020\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0019 - mean_squared_error: 0.0019 - val_loss: 0.0020 - val_mean_squared_error: 0.0020\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 5s 1ms/step - loss: 0.0019 - mean_squared_error: 0.0019 - val_loss: 0.0018 - val_mean_squared_error: 0.0018\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_90_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_90_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3371/3375 [============================>.] - ETA: 0s - loss: 0.3227 - mean_squared_error: 0.3227WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_90_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 6s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 6s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 6s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_117_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_117_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3353/3375 [============================>.] - ETA: 0s - loss: 0.3227 - mean_squared_error: 0.3227WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_117_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 10s 3ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 10s 3ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 10s 3ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 9s 3ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_144_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_144_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3370/3375 [============================>.] - ETA: 0s - loss: 0.3227 - mean_squared_error: 0.3227WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_144_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 9s 3ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 9s 3ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 9s 3ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_171_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_171_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3364/3375 [============================>.] - ETA: 0s - loss: 0.0390 - mean_squared_error: 0.0390WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_171_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0390 - mean_squared_error: 0.0390 - val_loss: 0.0372 - val_mean_squared_error: 0.0372\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0372 - mean_squared_error: 0.0372 - val_loss: 0.0371 - val_mean_squared_error: 0.0371\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0372 - mean_squared_error: 0.0372 - val_loss: 0.0371 - val_mean_squared_error: 0.0371\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0372 - mean_squared_error: 0.0372 - val_loss: 0.0372 - val_mean_squared_error: 0.0372\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 6s 2ms/step - loss: 0.0372 - mean_squared_error: 0.0372 - val_loss: 0.0371 - val_mean_squared_error: 0.0371\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 6s 2ms/step - loss: 0.0372 - mean_squared_error: 0.0372 - val_loss: 0.0372 - val_mean_squared_error: 0.0372\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0372 - mean_squared_error: 0.0372 - val_loss: 0.0372 - val_mean_squared_error: 0.0372\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 6s 2ms/step - loss: 0.0372 - mean_squared_error: 0.0372 - val_loss: 0.0371 - val_mean_squared_error: 0.0371\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 6s 2ms/step - loss: 0.0372 - mean_squared_error: 0.0372 - val_loss: 0.0372 - val_mean_squared_error: 0.0372\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0372 - mean_squared_error: 0.0372 - val_loss: 0.0371 - val_mean_squared_error: 0.0371\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_198_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_198_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3364/3375 [============================>.] - ETA: 0s - loss: 0.3227 - mean_squared_error: 0.3227WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_198_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 10s 3ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 9s 3ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 10s 3ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_225_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_225_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3360/3375 [============================>.] - ETA: 0s - loss: 0.0379 - mean_squared_error: 0.0379WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_225_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0379 - mean_squared_error: 0.0379 - val_loss: 0.0386 - val_mean_squared_error: 0.0386\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0375 - mean_squared_error: 0.0375 - val_loss: 0.0374 - val_mean_squared_error: 0.0374\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 9s 3ms/step - loss: 0.0373 - mean_squared_error: 0.0373 - val_loss: 0.0371 - val_mean_squared_error: 0.0371\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0374 - mean_squared_error: 0.0374 - val_loss: 0.0373 - val_mean_squared_error: 0.0373\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.0374 - mean_squared_error: 0.0374 - val_loss: 0.0372 - val_mean_squared_error: 0.0372\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0374 - mean_squared_error: 0.0374 - val_loss: 0.0376 - val_mean_squared_error: 0.0376\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.0374 - mean_squared_error: 0.0374 - val_loss: 0.0372 - val_mean_squared_error: 0.0372\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0374 - mean_squared_error: 0.0374 - val_loss: 0.0378 - val_mean_squared_error: 0.0378\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.0374 - mean_squared_error: 0.0374 - val_loss: 0.0373 - val_mean_squared_error: 0.0373\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0374 - mean_squared_error: 0.0374 - val_loss: 0.0372 - val_mean_squared_error: 0.0372\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_252_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_252_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3370/3375 [============================>.] - ETA: 0s - loss: 0.0495 - mean_squared_error: 0.0495WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_252_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0494 - mean_squared_error: 0.0494 - val_loss: 0.0371 - val_mean_squared_error: 0.0371\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0372 - mean_squared_error: 0.0372 - val_loss: 0.0371 - val_mean_squared_error: 0.0371\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 6s 2ms/step - loss: 0.0372 - mean_squared_error: 0.0372 - val_loss: 0.0371 - val_mean_squared_error: 0.0371\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 6s 2ms/step - loss: 0.0372 - mean_squared_error: 0.0372 - val_loss: 0.0371 - val_mean_squared_error: 0.0371\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0372 - mean_squared_error: 0.0372 - val_loss: 0.0371 - val_mean_squared_error: 0.0371\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0372 - mean_squared_error: 0.0372 - val_loss: 0.0371 - val_mean_squared_error: 0.0371\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0372 - mean_squared_error: 0.0372 - val_loss: 0.0371 - val_mean_squared_error: 0.0371\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0372 - mean_squared_error: 0.0372 - val_loss: 0.0371 - val_mean_squared_error: 0.0371\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0372 - mean_squared_error: 0.0372 - val_loss: 0.0372 - val_mean_squared_error: 0.0372\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 6s 2ms/step - loss: 0.0372 - mean_squared_error: 0.0372 - val_loss: 0.0371 - val_mean_squared_error: 0.0371\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_279_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_279_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3374/3375 [============================>.] - ETA: 0s - loss: 0.3227 - mean_squared_error: 0.3227WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_279_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 9s 3ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 8s 3ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.3227 - mean_squared_error: 0.3227 - val_loss: 0.3202 - val_mean_squared_error: 0.3202\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_306_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_306_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3362/3375 [============================>.] - ETA: 0s - loss: 0.0089 - mean_squared_error: 0.0089WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_306_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (32, 10).\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.0088 - mean_squared_error: 0.0088 - val_loss: 0.0041 - val_mean_squared_error: 0.0041\n",
      "Epoch 2/10\n",
      "3375/3375 [==============================] - 9s 3ms/step - loss: 0.0041 - mean_squared_error: 0.0041 - val_loss: 0.0041 - val_mean_squared_error: 0.0041\n",
      "Epoch 3/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.0038 - mean_squared_error: 0.0038 - val_loss: 0.0037 - val_mean_squared_error: 0.0037\n",
      "Epoch 4/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.0037 - mean_squared_error: 0.0037 - val_loss: 0.0036 - val_mean_squared_error: 0.0036\n",
      "Epoch 5/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.0036 - mean_squared_error: 0.0036 - val_loss: 0.0034 - val_mean_squared_error: 0.0034\n",
      "Epoch 6/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.0035 - mean_squared_error: 0.0035 - val_loss: 0.0037 - val_mean_squared_error: 0.0037\n",
      "Epoch 7/10\n",
      "3375/3375 [==============================] - 7s 2ms/step - loss: 0.0034 - mean_squared_error: 0.0034 - val_loss: 0.0038 - val_mean_squared_error: 0.0038\n",
      "Epoch 8/10\n",
      "3375/3375 [==============================] - 9s 3ms/step - loss: 0.0034 - mean_squared_error: 0.0034 - val_loss: 0.0036 - val_mean_squared_error: 0.0036\n",
      "Epoch 9/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.0034 - mean_squared_error: 0.0034 - val_loss: 0.0034 - val_mean_squared_error: 0.0034\n",
      "Epoch 10/10\n",
      "3375/3375 [==============================] - 8s 2ms/step - loss: 0.0033 - mean_squared_error: 0.0033 - val_loss: 0.0033 - val_mean_squared_error: 0.0033\n"
     ]
    }
   ],
   "source": [
    "from tensorflow.keras import Sequential\n",
    "from tensorflow.keras.layers import Dense\n",
    "from tensorflow.keras.optimizers import SGD, RMSprop, Adam\n",
    "from tensorflow.keras.metrics import MeanSquaredError as MSE\n",
    "from tensorflow.keras.losses import MeanSquaredError\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "def create_model(hidden_layers, optimizer, features):\n",
    "    model = Sequential()\n",
    "    model.add(Dense(12, activation='relu', input_shape=(32, 10)))\n",
    "    for i in range(hidden_layers):\n",
    "        model.add(Dense(8, activation = 'relu'))\n",
    "    model.add(Dense(1, activation = 'relu'))\n",
    "    model.compile(optimizer=optimizer, loss='mse', metrics=MSE())\n",
    "    return model\n",
    "\n",
    "learning_rates = [0.1, 0.01, 0.001]\n",
    "optimizers = [SGD, RMSprop, Adam]\n",
    "layers = [1, 5, 25]\n",
    "\n",
    "accs = pd.DataFrame()\n",
    "val_accs = pd.DataFrame()\n",
    "losses = pd.DataFrame()\n",
    "val_losses = pd.DataFrame()\n",
    "models = []\n",
    "\n",
    "for num_layers in layers:\n",
    "    for learning_rate in learning_rates:\n",
    "        for optimizer in optimizers:\n",
    "            opt = '-'.join(str(optimizer).split(\"'\")[1].split(\".\")[-2:])\n",
    "            model = create_model(num_layers, optimizer(learning_rate=learning_rate), 10)\n",
    "            history = model.fit(X_train, y_train, epochs=10, validation_data=(X_test,y_test), batch_size=32, verbose=1,\n",
    "          validation_split=0.1).history\n",
    "            accs[f'{num_layers}-{learning_rate}-{opt}'] = history['mean_squared_error'] \n",
    "            val_accs[f'{num_layers}-{learning_rate}-{opt}'] = history['val_mean_squared_error'] \n",
    "            losses[f'{num_layers}-{learning_rate}-{opt}'] = history['loss'] \n",
    "            val_losses[f'{num_layers}-{learning_rate}-{opt}'] = history['val_loss'] \n",
    "            models.append(model)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "091cef5b",
   "metadata": {},
   "source": [
    "## Plot learning curves for all combinations"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "12595085",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "\n",
    "for i in accs.columns:\n",
    "    x_plot = np.linspace(1, 10, 10)\n",
    "    fig, axes = plt.subplots()\n",
    "    axes.plot(x_plot, losses[i], label='loss')\n",
    "    axes.plot(x_plot, val_losses[i], label='val_loss')\n",
    "    axes.set_xlabel('epochs')\n",
    "    axes.set_ylabel('losses')\n",
    "    fig.legend(['train', 'test'], loc='upper right')\n",
    "    fig.savefig(os.path.join(f'C:/Users/Iryna.Dosiak/results/{str(i)}.png'))\n",
    "    plt.close(fig)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b9c473ab",
   "metadata": {},
   "source": [
    "## Collect results"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "5be93e2e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_3_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_6_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_9_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_12_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_15_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_18_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_21_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_24_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_27_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_34_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_41_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_48_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_55_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_62_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_69_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_76_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_83_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_90_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_117_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_144_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_171_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_198_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_225_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_252_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_279_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 32, 10) for input Tensor(\"dense_306_input:0\", shape=(None, 32, 10), dtype=float32), but it was called on an input with incompatible shape (None, 10).\n"
     ]
    }
   ],
   "source": [
    "results = []\n",
    "for i in range(27):\n",
    "    results.append([accs.columns[i], models[i].evaluate(X_test, y_test, verbose=0)[0]])\n",
    "results_df = pd.DataFrame(results)\n",
    "writer = pd.ExcelWriter('C:/Users/Iryna.Dosiak/results.xlsx', engine='xlsxwriter')\n",
    "results_df.to_excel(writer, sheet_name='results', index=False)\n",
    "writer.save()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8d2e3934",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
